{
 "title": "Tarpit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "lookup_ip", "label": "Look up IP" }
  ]
 },
 "panels": [
  { "title": "Specifics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Details for ${lookup_ip}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM ssh_connections\nWHERE CASE\n        WHEN '${lookup_ip}' = '' THEN FALSE\n        ELSE client_ip = '${lookup_ip}'::inet\n      END;"
    }
   ]
  },
  { "title": "Tarpit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Currently trapped",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(active_connections) from ssh_connections"
    }
   ]
  },
  {
   "title": "Total time wasted",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(total_time_wasted) from ssh_connections"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(connections) from ssh_connections"
    }
   ]
  },
  {
   "title": "Latest 5 connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
   "targets": [
    {
     "rawSql": "select client_ip,connections,last_seen,country_code from ssh_connections order by last_seen desc limit 5"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "rawSql": "select client_ip,active_connections,last_seen,country_code from ssh_connections where active_connections > 0 ORDER by last_seen desc limit 5"
    }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(sent_bytes) from ssh_connections"
    }
   ]
  },
  {
   "title": "Unique addresses",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from ssh_connections"
    }
   ]
  },
  {
   "title": "Country leaderboard by conns",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select sum(connections) as connections, country_code from ssh_connections GROUP BY country_code order by connections desc\n"
    }
   ]
  },
  {
   "title": "Country leaderboard by time wasted",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select sum(total_time_wasted) as wasted, country_code from ssh_connections GROUP BY country_code order by wasted desc\n"
    }
   ]
  },
  {
   "title": "Top version strings",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(icv.client_ip) AS ip_count,\n    version\nFROM \n    client_versions cv\nINNER JOIN \n    ip_client_versions icv ON cv.id = icv.version_id\nGROUP BY \n    cv.id\nORDER BY \n    ip_count desc\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Most desperate",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 5, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT client_ip, max_concurrent, last_seen, total_time_wasted, country_code from ssh_connections order by max_concurrent desc limit 10"
    }
   ]
  },
  {
   "title": "Most seen ASN",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 26 },
   "targets": [
    {
     "rawSql": "select count(client_ip) as ips, asn from ssh_connections GROUP BY asn order by ips desc limit 10;"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \n    latitude AS \"latitude\",\n    longitude AS \"longitude\",\n    client_ip AS \"name\",\n    last_seen AS \"time\",\n    connections AS \"connections\",\n    total_time_wasted AS \"total_time_wasted\",\n    active_connections AS \"active_connections\"\nFROM ssh_connections\nWHERE latitude IS NOT NULL AND longitude IS NOT NULL and active_connections > 0"
    }
   ]
  },
  {
   "title": "All locations",
   "type": "geomap",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  latitude AS \"latitude\",\n  longitude AS \"longitude\",\n  client_ip AS \"name\",\n  last_seen AS \"time\",\n  total_time_wasted\nFROM ssh_connections\nWHERE latitude IS NOT NULL AND longitude IS NOT NULL\n  AND total_time_wasted IS NOT NULL\nORDER BY total_time_wasted;"
    }
   ]
  }
 ]
}